# Generated by Django 4.1.4 on 2022-12-16 12:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='author',
        ),
        migrations.AddField(
            model_name='book',
            name='authors',
            field=models.CharField(default=None, max_length=1000, verbose_name='authors'),
            preserve_default=False,
        ),
    ]
